baseURL: "https://hossainemruz.github.io/"
languageCode: "en-us"
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-123-45

# Enable Disqus forum
disqusShortname: hossainemruz-github-io

# Enable global emoji support
enableEmoji: true

# Menus of the home page
menus:
  main:
  - name: Home
    url: "#home"
    weight: 1
  - name: About
    url: "#about"
    weight: 2
  - name: Skills
    url: "#skills"
    weight: 3
  - name: Experiences
    url: "#experiences"
    weight: 4
  - name: Projects
    url: "#projects"
    weight: 5
  - name: Recent Posts
    url: "#recent-posts"
    weight: 6
  - name: Achievements
    url: "#achievements"
    weight: 7

# Optional site parameters
params:
  logo: assets/images/logos/project-default.png
  contactInfo:
    email: hossainemruz@gmail.com
    phone: "+8801770582121"
